source/m3.h
source/m3_exec.c

Fixes #2 
I ran the applicable tests and they pass now.
Note that not all the call indirect tests pass, but the remaining failure I believe is for a different and unrelated reason (looks like a stack overflow on `call_indirect.wast:263`).

Implement trap on indirect call type mismatch

---

source/m3_env.c
source/m3_env.h

Deleted `m3_GetMemory()` declaration in `m3_env.h` as there it is also declared (with a slightly different signature) in `m3.h`
Adapted function definition in `m3_env.c` to conform to the remaining `m3.h` function declaration.
(Tested linear memory access by invoking get/set string functions through raw pointer returned by `m3_GetMemory()`: works correctly!)

Minor changes to m3_GetMemory

---

platforms/app/main.c
source/m3_api_wasi.c
source/m3_env.h

This is a proposed PR for fixing #58 
When running a file (non-REPL mode), if the proc_exit call is called,
then terminate with the exit code. If in REPL mode then print
a message with the exit code to indicate the wasi call was made and
continue.

wasi/main: return exit code on wasi proc_exit call

---

docs/Performance.md
platforms/esp32-idf/main/CMakeLists.txt
platforms/esp32-idf/sdkconfig.defaults
source/m3_math_utils.h

- Fix warning about `signbit` redefined (happens with the newer toolchain releases in IDF 4.1 and later)
- platforms/esp32: optimize WASM3 source for performance, update the benchmark table.

Minor ESP32 fixes

---

source/m3_core.h
source/m3_env.c
source/m3_module.c

Running the esp32-idf-wasi application in heap profiler has revealed a few memory leaks. This PR fixes the leaks.
A future TODO may be to run some tests in CI under valgrind.

Fix several memory leaks

---

platforms/esp32-idf-wasi/main/m3_api_esp_wasi.c
source/m3_api_wasi.c
source/m3_compile.c
source/m3_config_platforms.h
source/m3_core.c
source/m3_env.c
source/m3_info.c

This reverts the change introduced in b087435, that made min/max
definitions conditional on !__cplusplus. Since some use cases of wasm3
require its C source files to be compiled with a C++ compiler, that
change resulted in min/max being undefined for WASMM3 source files.
This commit makes min/max macros scoped with m3_ prefix, which
resolves the conflict with min/max member functions defined in the STL
and elsewhere.
Closes https://github.com/wasm3/wasm3/issues/92

prefix min and max macros with m3_ to avoid conflicts with the STL

---

source/m3_exec.h

Compare approaches her:
https://godbolt.org/z/URTGNG

[optimize] Use branchless clz / ctz for x86 (before AVX2 on Intel & ABM+BMI1 on AMD)

---

docs/Hardware.md

Just tested wasm3 with a Sparkfun Photon RedBoard (Particle P1) and wanted to add it to the list of tested devices. Works like a charm.
https://www.sparkfun.com/products/13321
Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

add sparkfun photon redboard to tested device list

---

source/m3_bind.c
source/m3_exec.c
source/m3_exec.h
source/wasm3.h

This PR allows a client code to register native function as callback.
There was already a mecanism to do that, but the callback signature did not have any information beyond the M3 normal context (runtime, sp and mem).
The extended mecanism allows the client to specify a uin64 cookie value that will be given to the native callback when called.
This is useful because if you want to register hundreds of callbacks, with the previous mecanism you had to define hundreds of callback functions, this was not scaling.

allow for dynamic callbacks

---

source/m3_env.c
source/wasm3.h

Example use is here: https://github.com/wasmx/fizzy/blob/master/test/utils/wasm3_engine.cpp#L69
I'm not sure this is accepted upstream, but I am interested in feedback.

Make m3_GetMemory non-const

---

.github/workflows/tests.yml
CMakeLists.txt
test/run-wasi-test.py

This release focuses on improving the robustness of the path resolution and sandboxing, including support for relative preopen paths.
This addresses https://github.com/wasm3/wasm3/pull/126#issuecomment-618095571.

update uvwasi to version 0.0.8

---

.github/workflows/tests.yml

The QEMU CI appears to be broken because the calculation to determine the QEMU version to install now returns multiple versions. This commit updates the logic to take the last result (which I think will be the newest version).

build: use last matching qemu version

---

CMakeLists.txt
source/m3_api_uvwasi.c

Notable changes:
- A `DEBUG()` macro and `UVWASI_DEBUG_LOG` build option have been
added to improve debugging.
- Path length restrictions have been removed across the codebase.
- Initial support for `poll_oneoff()` has been added on all
platforms. The implementation is based on `uv_poll_t`'s.
- A new `uvwasi_size_t` has been introduced across the WASI system
call API. This provides consistent 32-bit `size_t`'s.
- The cmake test targets are now only generated if uvwasi is the
root project to avoid conflicts with targets from embedders.
- `uv.h` has been removed from the public headers.
- A serialization/deserialization API has been added to simplify
the process of working with WASM memory. This also hides many
WASI <--> WASM interfacing implementation details from
embedders.
- A memory …

update uvwasi to version 0.0.9

---

source/m3_env.c

I was running some benchmarking with a wasm blob which uses a start function (compiled with AssemblyScript) and noticed I get a bunch of `Result: <Empty Stack>` messages. It seemed that can only be emitted in `m3_CallWithArgs`, a function I do not use, and while tracking down how the start function is handled in wasm3 I realised it goes through `m3_CallWithArgs`.
This PR removes that dependency on the external API and comes with a benefit: it ensures the proper type for the start function. `master` only checks that start takes no arguments, but doesn't validate that it it should not return anything.

Implement InitStartFunc without m3_Call and ensure the correct function type

---

CMakeLists.txt
source/m3_api_uvwasi.c

Notable changes:
- The `uvwasi_preopen_t` now uses `const char*` for the `mapped_path` and `real_path` fields. Previously, these were not `const`.
- `uvwasi_path_filestat_get()` now properly handles the `UVWASI_LOOKUP_SYMLINK_FOLLOW` flag.
- `uvwasi_options_init()` has been added to reduce the boilerplate code associated with initializing `uvwasi_options_t`'s.
- The `DEBUG()` macro has been renamed to `UVWASI_DEBUG()` to reduce naming conflicts with other projects.
- The `uvwasi_fd_filestat_set_times()` and `uvwasi_path_filestat_set_times()` functions now have proper implementations.
- Several issues have been addressed in `uvwasi_fd_readdir()`. A bug in the copying of the directory entry's name has been fixed. The function now returns `UVWASI_ENOSYS` on Windows and Android. Serdes …

update uvwasi to version 0.0.11

---

source/m3_parse.c

I noticed what looked to me like a copy-pasta error when perusing through the code. Specifically, around the check for the position of the data count section which has an ID of 12 but comes before the code section.
As a side note the `section == 12 and previousSection == 9` check is not strictly necessary since `(section = 12) > (previousSection = 9)`, but it is informative so I left it in.

Fix check for data count section ordering

---

CMakeLists.txt

uvwasi was transferred into the Node.js GitHub org.
This commit updates the repository's link.

update uvwasi repo

---

platforms/cosmopolitan/build.sh

@vshymanskyy per our discussion at https://github.com/jart/cosmopolitan/issues/32 here's a small change that might solve your build issue. It's not clear to me yet why this causes the cryptic linker error to go away. It is however a best practice in general to do this, since you'll want the debug info. Please let me know if this change resolves things on your end.

Fix Wasm3 Cosmopolitan build config

---

platforms/python/m3module.c
source/m3_compile.c
source/m3_config.h
source/m3_env.c
source/m3_env.h
source/m3_exec.h
source/m3_info.c
source/m3_module.c
source/m3_parse.c

This pull request addresses #198.
I would be happy to add a test to the [Core test suite](https://github.com/wasm3/wasm-core-testsuite), but it wasn't immediately clear to me how to do so. It seems likely I'd need to add a test to [exports.json](https://github.com/wasm3/wasm-core-testsuite/blob/master/core/exports.json), but I haven't yet dug down into the test suite to figure out how to do so.
A simple Wasm module that illustrates this problem can be found in #198, but I'll reproduce it here:
```wasm
(module
(type (;0;) (func (result i32)))
(func (;0;) (type 0) (result i32)
i32.const 42)
(export "first" (func 0))
(export "second" (func 0)))
```

Support exported functions with the same name

---

source/m3_parse.c

#198 contained a bug in which one fewer function name than `d_m3MaxDuplicateFunctionImpl` could be saved for a given function implementation. I caught this when preparing the [WebAssembly spec test pull request](https://github.com/WebAssembly/spec/pull/1289).
Arithmetic is hard. Sorry.

Fix off-by-one error in ParseSection_Export()

---

source/m3_env.c
source/m3_env.h

I think this fixes #203. At least it does on our CI.

Remove memory leak caused by dangling retFuncTypes in M3Environment

---

.github/workflows/tests.yml
extra/testutils.py
platforms/python/examples/pygame-raytrace.py
test/run-spec-test.py

Fixes some PEP8 issues with Python code
% `flake8 . --max-line-length=156 --select=E7 --statistics`
```
./platforms/python/examples/pygame-raytrace.py:55:12: E703 statement ends with a semicolon
./test/run-spec-test.py:101:50: E713 test for membership should be 'not in'
./test/run-spec-test.py:130:28: E701 multiple statements on one line (colon)
./test/run-spec-test.py:265:25: E711 comparison to None should be 'if cond is None:'
./test/run-spec-test.py:285:42: E711 comparison to None should be 'if cond is None:'
./test/run-spec-test.py:408:27: E711 comparison to None should be 'if cond is not None:'
./test/run-spec-test.py:451:23: E701 multiple statements on one line (colon)
./extra/testutils.py:46:40: E711 comparison to None should be 'if cond is not None:'
2     E701 multiple statements …
```

Python: Drop EOL Py35 and fix flake8 --select=E7 issues

---

source/m3_env.c
source/m3_parse.c

While trying to integrate wasm3 in my projects that has some warnings enabled, I hit 2 errors caused by `-Wmissing-field-initializers`:
```
/Users/jf/wasm3/source/m3_parse.c:294:71: warning: missing field 'lastOpcodeStart' initializer [-Wmissing-field-initializers]
    compilation = (M3Compilation){ NULL, io_module, * io_bytes, i_end };
```
Using designated initialisers to initialize the structs makes the warning disappear, and also makes the code a little bit more explicit.

Support compilation with -Wmissing-field-initializers

---

CMakeLists.txt

Clang on M1 does not support `-march=native`, so a clean pull and attempt to build of wasm3 fails on these computers. This PR fixes that situation by detecting when user is building on _Apple_ computer using _clang_ compiler and host processor is _arm64_ - using `-mcpu=native` flag instead. 
Building on M1 when using shell as native host:
```sh
$ mkdir -p build && cd build && cmake .. && make
...
Release flags: -O3 -Wfatal-errors -fomit-frame-pointer -fno-stack-check -fno-stack-protector -mcpu=native
...
$ file wasm3
wasm3: Mach-O 64-bit executable arm64
```
Building on M1 when using shell as x86_64 host:
```sh
$ arch -x86_64 bash
$ mkdir -p build && cd build && cmake .. && make
...
Release flags: -O3 -Wfatal-errors -fomit-frame-pointer -fno-stack-check -fno-stack-protector -march=native …
```

Support building on macOS with M1 chip

---

platforms/cpp/wasm3_cpp/include/wasm3_cpp.h

This PR contains two improvements for the C++ wrapper:
1. Use `m3_Call` in `function::call`, getting rid of string conversions.
When `function::call` was first written, `m3_Call` did not exist yet, and the only way to call functions was through `m3_CallArgv` which takes arguments as strings. Now that `m3_Call` is available, string conversion can be removed.
Closes https://github.com/wasm3/wasm3/issues/219.
2. Use m3ApiGetArg, m3ApiReturn, m3_GetResults for stack access, resolving some FIXMEs.
The code still relies on an internal m3_api_defs.h header, but at least it is less likely to get broken, and doesn't depend on `M3Runtime` internals.

platforms/cpp: use m3_Call and stack access API

---

platforms/embedded/esp32-idf-wasi/main/main.cpp
platforms/embedded/esp32-idf/main/main.cpp
platforms/embedded/esp32-pio/src/main.cpp

1. Use m3_GetResultsV instead of accessing the stack directly.
2. Print the actual chip target name instead of the hard-coded ESP32.

platforms/esp32: trivial fixes

---

source/wasm3.h

Apart from being a warning, this is technically also an instance of undefined behavior: only uintptr_t should be used to convert between pointers and integers.

Fix GCC warning: cast from pointer to integer of different size

---

platforms/app/main.c
source/m3_core.c
source/m3_env.c
source/m3_exception.h
source/m3_exec.h
source/m3_math_utils.h
source/wasm3_defs.h

Also remove old unprefixed macros

Use M3_ prefix for likely/unlikely. Add likely in MemCopy/MemFill functions

---

build.zig
docs/Development.md

The minimal `build.zig` script effectively acts as a (nicer?) alternative to CMake; however, it is minimal in the sense, it currently only includes the necessary ingredients to build `wasm3` with Zig as the build system. As an added bonus though, you get the full cross-compilation power of Zig for free.
Example invocation to build for the host:
```
zig build
```
To target `wasm32-wasi` (currently depends on https://github.com/ziglang/zig/pull/8992):
```
zig build -Dtarget=wasm32-wasi
```
To target `aarch64-macos` from *anywhere* (currently depends on https://github.com/ziglang/zig/pull/9045 due to missing libc macOS headers shipped with Zig):
```
zig build -Dtarget=aarch64-macos
```

Add minimal build.zig build script

---

platforms/cpp/wasm3_cpp/include/wasm3_cpp.h

In cpp wrapper, add template specialization to `call` and `call_argv` for calling functions with void return type (closes #256).

cpp: add specialization for call with void return type

---

source/m3_code.c
source/m3_code.h
source/m3_env.c
source/m3_env.h

**In this pull request I moved `static local s_sequence` varible from `NewCodePage`-function to `M3Runtime`-structure.**
Rationale
Investigated multithreading (case1) and multimodule (case 2) usage of wasm3.
- Case 1:
```cpp
thread_1:
auto wasm1 = new wasm3_instance(wasm_module);
wasm1->execute_some_functions();
...
...
thread_N:
auto wasmN = new wasm3_instance(wasm_module);
wasmN->execute_some_functions();
...
```
- Case 2:
```cpp
main thread:
auto wasm1 = new wasm3_instance(wasm_module);
...
auto wasmN = new wasm3_instance(wasm_module);
wasm1->execute_some_functions();
...
wasmN->execute_some_functions();
```	
In wasm3 sources I found many of global variables.  
Most of them are `const` so don't think they are big problem.  
There are also non-const global variables and static local …

Moved static local varible from `NewCodePage`-function to `M3Runtime`-structure

---

source/wasm3.h

Rust bindgen which automatically generates bindings can now identify this as const static data and produce a signature with the correct mutability.
eg.
```rust
extern "C" {
pub static m3Err_mallocFailed: M3Result;
}
```
vs
```rust
extern "C" {
pub static mut m3Err_mallocFailed: M3Result;
}
```

Make error constants const

---

source/wasm3_defs.h

The branch for gcc < 4.8 includes endian.h unconditionally. Unfortunately endian.h is non-standard and is limited to linux according to the docs.
This breaks compilation for OSX PPC

Don't include endian.h unconditionally

---

source/wasm3_defs.h

This is an addendum to my previous patch as it missed to ensure inclusion of
some header that provides uint*. It worked for me only because of local flags
to add this include

w3_defs.h: Ensure that endian.h or stdint.h is included before using uint

---

.github/workflows/tests.yml
source/m3_api_wasi.c
source/m3_config_platforms.h

This PR makes a few trivial changes to confer Cygwin compatibility. A CI job is added to prevent regressions.

Fix Cygwin compatibility

---

source/m3_compile.c

I recently ported wasm3 to my kernel, [chariot](https://github.com/ChariotOS/chariot), and tried to run the coremark test. I'm not sure if this is a problem with any part of my libc, or a problem with wasm3's compiler, but this little change fixed the segfault/assertion failure on line 743. I'm not even sure if this is the correct place in the code to fix the bug.
If this is a problem with my libc/libm and not wasm3 feel free to deny this PR, but I figured I'd provide my fix in case it is helpful.

Check for if slot == c_slotUnused in PushConst

---

.github/workflows/tests.yml
source/m3_compile.c
source/m3_env.c
source/m3_env.h

Issue #321: This replaces `intValue` in the global value union with
separate `i32Value` and `i64Value`. A CI test is added against s390x.

Fix parsing of i32 constant globals on big-endian systems.

---

platforms/cpp/wasm3_cpp/include/wasm3_cpp.h

This change is to address #368. Standard C++ does not allow zero length arrays, this only works with compiler extensions. This change replaces the use a C array with an std:array which can be of length zero, but is still statically sized at compile time (e.g. `.size()` is `constexpr`).

Replace C array with std::array to handle zero length

---

source/m3_code.c
source/m3_compile.c

This PR attempts to fix all the open security-relevant issues found by OSS-Fuzz:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33457: There was an integer overflow when computing `pageSize`. Fixed in c71d965fe9790f635e08c64b5528c6a16fad91ac
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33554: wasm3 was crashing when trying to push a `Const64` value on the stack. The compilation is supposed to detect stack overflows before execution, but it failed to keep track of slots in context outside of a function (which seems to be the case when evaluating expressions in `InitElements`). Fixed in b1278b80a0cf7d36537c8d070e7e9c5f53c31246
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33555: While pushing the params back onto the stack in `CompileBlock`, …

Fix memory safety issues found by OSS-Fuzz

---

CMakeLists.txt

Improved the if case for detecting MSVC frontend that only triggers on clang-cl/msvc.
The wasm3 excecutable has some linking issues but the library can be built & used.

Support standalone clang with GCC frontend

---

source/m3_env.c
source/m3_function.h
source/m3_parse.c

Since https://reviews.llvm.org/D81689, wasm-ld has started wrapping
all exported functions including "_start" with surrounding ctor/dtor
calls. The wrapper function "_start.command_export" is exposed as
"_start".
wasm3 searched the entry function by looking up names indiscriminately.
However, it sometimes found the internal "_start" function, so ctor/dtor
were not called. To pick up the wrapper "_start", this patch changes to
search export names at first.
This issue has been found in SwiftWasm project https://github.com/swiftwasm/swift/issues/4437

m3_env.c: prefer export name in searching function

---

platforms/cpp/wasm3_cpp/include/wasm3_cpp.h

With C++ enum classes, the size of an enum object can vary depending
on the compiler generation mechanism (choosing the most optimal storage size
to contain all the variants) or a user-defined storage type. In wasm, we
can only send int32_t and int64_t. That means, the enums using this
integer width for storage must also work properly. At runtime this works
flawlessly, the functions in wasm can return these values safely and
they are even converted back on the C++ side to their enum
representations, thanks to the code in wasm3 which does a cast an
integer cast. But when it comes to generating the code for function
arguments, the defined data structure is not enough to generalize the
code to allow enum classes even if they are of a proper (allowed) width.
This commit changes the defined …

Allow C++ enum classes to be marshalled as integers when possible.

---

source/m3_exec.h

If the compiler cannot analyze memcpy, it must expect that pointer arguments may be stored as static data and must live for recursive calls. In such cases, op_Store and op_Load operations will not get tail-call optimized. By enclosing the local variables in a block before the recursive call, the storage duration does not extend far enough, allowing for TCO.
Closes #401 
Assembly code emitted after fix:
Notice the call at `+110` is a tail-call now.
```
Dump of assembler code for function op_i32_Store_i32_ss:
0x000113ac <+0>:	stmdb	sp!, {r4, r5, r6, r7, r8, r9, lr}
0x000113b0 <+4>:	mov	r5, r0
0x000113b2 <+6>:	mov	r7, r2
0x000113b4 <+8>:	mov.w	r12, #0
0x000113b8 <+12>:	mov	r6, r1
0x000113ba <+14>:	vpush	{d8}
0x000113be <+18>:	ldr	r3, [r0, #4]
0x000113c0 <+20>:	sub	sp, #20
0x000113c2 <+22>: …
```

Fix operations preventing tail-call-elimination:

---

source/m3_core.h

This commit bumps up some default limit values to align with some mainstream implementations, and allows wasm3 to execute some larger wasm32 modules that it would previously report errors like "too many functions" and such. There are specialized m3_core.h for more restricted platforms, and this commit doesn't touch those, so it shouldn't increase the overhead on those platforms.
Wasm spec discussion: https://github.com/WebAssembly/spec/issues/607
V8 limits: https://chromium.googlesource.com/v8/v8/+/master/src/wasm/wasm-limits.h
SpiderMonkey limits: https://hg.mozilla.org/mozilla-central/file/tip/js/src/wasm/WasmConstants.h
JavaScriptCore limits: https://github.com/WebKit/WebKit/blob/main/Source/JavaScriptCore/wasm/WasmLimits.h

Bump up some default limits to align with mainstream wasm implementations

---

source/m3_compile.c

Reserve numConstantSlots should make sure less than d_m3MaxConstantTableSize. Or it will fail in `PushConst`:
```c
d_m3Assert(constTableIndex < d_m3MaxConstantTableSize);
```

fix consts limit bug

---

build.zig

`addIncludeDir()` was renamed to `addIncludePath()`.

Fix build.zig file for Zig 0.10

---

CMakeLists.txt

This bumps the uvwasi dependency version
from 0.0.12 (Nov 2021) to 0.0.14 (Dec 2022).

update to uvwasi 0.0.14

---

source/m3_env.c
source/m3_exec.h
source/m3_exec_defs.h

When `OpProfiling` or `OpTracing` is enabled, wasm3 fails to build with clang-16 because the signature of the function with `__attribute__(musttail)` are incompatible with the calling function.  For instance, the funciton `profileOp` has 6 parameters, but its caller function `RunCode` only has 5. Therefore, to satisfy the requirement of using `__attribute__(musttail)`, I modify function signatures of these functions.

Fix functions with musttail attribute

---

source/m3_env.c
source/m3_env.h

The statement [`runtime->stack = stack_backup;`](https://github.com/wasm3/wasm3/blob/772f8f4648fcba75f77f894a6050db121e7651a2/source/m3_exec.h#L651) during local function unwinding may not be executed.
This ultimately leads to using the wrong address when freeing the stack.

Fix the issue of incorrectly freeing the stack address when unwinding local functions.

---

source/m3_env.h
source/m3_parse.c

Adds a `module->memoryImport` (for import module/field names), and `module->memoryExportName` (for exported name) fields to the `M3Module` struct, and populates those values when appropriate during `m3_ParseModule()`.
Somewhat related to #110 and #137.

Allow for retrieval of "memory" type import / export name

---

source/m3_env.c

Fix to check the global mutability before setting new value.
resolve #319

Check global mutability

---

source/m3_env.c
source/wasm3.h

Resolves #101.
Rather than directly invoking functions by their index, this just allows `IM3Function` instances to be obtained by index, so they can then be called with the standard call functions.

Add `m3_GetTableFunction` to allow calling functions by index

---

source/m3_exec.h

[as the spec states](https://webassembly.github.io/spec/core/exec/numerics.html#op-iadd) integer add, sub, and mul should wrap on overflow.
the current implementation adds two signed integers, which is undefined behavior on overflow per the C standard (in my case, this triggered an `illegal execution`). this bugfix uses __builtin_add_overflow (and mul, sub variants) to make this behavior well defined.

bugfix: use gcc/clang compatible overflow builtins for integer arithmetic

---

.gitignore
build.zig

https://ziglang.org/download/0.13.0/release-notes.html
changes:
- update zig version
- switch between build libwasm3 only or wasm3+libwasm3 (since v0.11.0, help zig-pkg manager [a.k.a zon-file])
e.g.: https://github.com/kassane/wasm3-d/blob/main/build.zig.zon
close #454 
cc: @vshymanskyy

zig build: updated to v0.13.0
