wasm3/wasm3

- test/benchmark/coremark/README.md
Add Wasmer-JS as an easy way to test directly in Node/V8
> Add wasmer-js

- source/m3_api_wasi.c
+ m3_wasi_unstable_clock_res_get
+ some improvments
> Better handle getrandom. Add wasi_clock_res_get

- source/m3_api_wasi.c
> Try to fix wasi random function for different platforms

- README.md
WAPM just added support for package badges (inspired by this repo).
This PR uses the WAPM badge (which will be always up to date) :)
> Use official wapm badge

- source/m3_compile.c
- source/m3_exec.h
- test/run-spec-test.py
> Implement sign-extension opcodes

- source/m3_compile.c
- source/m3_exec.h
> specialize i32 bitwise operations

- docs/Hardware.md
* Fix Fomu flash size.
* Fix spelling mistake.
> Two minor documentation fixes

- platforms/ios/wasm3/ViewController.swift
- platforms/ios/wasm3/main.c
- Add native C fib bench for comparison
- minor enchantments
> Improve ios example

- source/m3_compile.c
a possible fix of this bug #104
> Fix of potential bug in the function Compile_Select

- source/CMakeLists.txt
Fixes: https://github.com/wasm3/wasm3/issues/107
> Build library target with WASI support

- CMakeLists.txt
- platforms/app/main.c
- source/CMakeLists.txt
- source/m3_api_uvwasi.c
- source/m3_api_wasi.c
- source/wasm3.h
Refs: https://github.com/wasm3/wasm3/issues/79
> add initial uvwasi integration

- source/m3_api_uvwasi.c
This commit fixes the last remaining WASI failure in the CI on linux-clang-x86.
> update fd_fdstat_get() result ABI

- source/m3_compile.c
I don't know why, I'm just finding this bug for many days, now here it is.
> fix PreserveArgsAndLocals bug

- source/m3_api_wasi.c
This fixed it for me on my fork, trying CI here
> Fix wasi openat

- README.md
- docs/Hardware.md
- platforms/esp32-idf-wasi/sdkconfig.defaults
- platforms/fomu/include/printf.h
- platforms/fomu/src/usb-desc.c
- source/m3_compile.c
- source/m3_exec.h
- source/m3_parse.c
- test/run-spec-test.py
- test/wasi/c-ray/c-ray-f.c
- test/wasi/stream/stream.c
Fixes #211 
Made various typo fixes to comments and markdown files.
> Fixed typos in relation to issue #211

- .github/workflows/tests.yml
Related to #212
Failing tests are unrelated to these changes.
Also, https://github.com/actions/setup-python/releases
> GitHub Actions: Add codespell to our tests

- CMakeLists.txt
This enables to inject this option from command-line
> Make BUILD_NATIVE to be an option

- platforms/cpp/wasm3_cpp/include/wasm3_cpp.h
Fixes for bug described in https://github.com/wasm3/wasm3/issues/271 issue.
> In cpp wrapper: added saving module raw data to module class

- platforms/cpp/wasm3_cpp/include/wasm3_cpp.h
Closes https://github.com/wasm3/wasm3/issues/295
> platforms/cpp: make the functions implemented in the header inline

- source/m3_api_meta_wasi.c
- source/m3_api_uvwasi.c
- source/m3_api_wasi.c
this is for issue https://github.com/wasm3/wasm3/issues/323
> fix WASI API read/write pread/pwrite buffer overflow

- source/m3_env.c
Issue: https://github.com/wasm3/wasm3/issues/363
> m3_Call*-functions fix

- source/wasm3.h
This PR adds support for multi return value for raw functions.
This ticks the box mentioned in this issue: https://github.com/wasm3/wasm3/issues/23
> feat: add support for multi return value for raw functions

- docs/Interpreter.md
> Fix: typos

- platforms/app/main.c
(I have no experience with this code base so someone should probably review this before merging.)
> Fix resource leaks

- README.md
url: https://github.com/kassane/wasm3-d
> readme: add wasm3-d
